---
- hosts: all
  # become_user: root
  # become: true
  tasks:
  - name: Install Package and Precheck
    apt: name={{ item }} state=latest
    with_items: 
      - lynis
    tags:
      - install
    
  - name: Run audit system...
    shell: lynis audit system > ~/ansiblar/tmp/audit.log
    tags: 
      - run-audit

  - name: Create signature
    shell: python3 ~/ansiblar/main.py sign
    tags: 
      - sign
  
  